### ISSUE TITLE
Removes `hiding (bla)` when it's useful

### ISSUE THREAD

**Issue by gromakovsky** [serokell/importify#58]
File: https://github.com/input-output-hk/cardano-sl/blob/importify-bug-2/rubbish/src/Command/Parser.hs
There is:
> import Universum hiding (show)
> import Prelude (read, show)
> parseCommand = first show . parse command ""

Importify deletes `hiding (show)` which breaks compilation:
```
[ 8 of 12] Command.Parser

/home/gromak/Work/cardano-sl/rubbish/src/Command/Parser.hs:193:22: error:
    Ambiguous occurrence ‘show’
    It could refer to either ‘Universum.show’,
                             imported from ‘Universum’ at src/Command/Parser.hs:7:1-26
                          or ‘Prelude.show’,
                             imported from ‘Prelude’ at src/Command/Parser.hs:13:52-55
                             (and originally defined in ‘GHC.Show’)
```
Importify version: 0b0fbe162297481a9480d23b2f4ea9531eed2d13

**Comment by ChShersh** [comment]
@gromakovsky This issue is fixed now in `master`.
