### ISSUE TITLE
Remove 'tasty-golden' dependency

### ISSUE THREAD

**Issue by ChShersh** [serokell/importify#61]
Executable `golden-generator` has `tasty-golden` library in dependencies but only needs `findByExtension` and `writeBinaryFile` functions from that library. It would be really great to remove this library from dependencies and implement our own versions of such functions (preferably using `path` and `path-io` libraries).

**Comment by mgttlinger** [comment]
I'll try to look at that if nobody else is already working on this

**Comment by ChShersh** [comment]
@mgttlinger Sure! Feel free to ask any questions :)

**Comment by mgttlinger** [comment]
When I try to run `stack test` I get the error 
```
importify-test: stack: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

`stack build` works though

**Comment by ChShersh** [comment]
@mgttlinger This is really strange. Which version of `stack` are you using?

I have no idea why this happens. But quick search suggests that something wrong with your `$PATH` variable: https://github.com/commercialhaskell/stack/issues/2282

Usually this error appears when program cannot find executable in `$PATH`. In your case it's `stack`. Maybe this is somehow related to `nix` if you're using it (I don't use it currently).

**Comment by kristoff3r** [comment]
I think he is using nix, I am too and I had the same problem. The reason for the error is that the test suite depends on stack, which isn't available inside the nix sandbox where the tester is run after being built. To fix it you can either run `stack test --nix-packages stack` or add `nix: packages: [stack]` to either this project's `stack.yaml` file or to `~/.stack/config.yaml`.

I propose adding it to the project, because then everything works out of the box for nix users.

**Comment by mgttlinger** [comment]
Yes I am using nix, sorry for not mentioning that. After adding that to the `stack.yaml` I get past this point but the `stack` instance started (by the tests?)  is still not using nix and therefore missing the right ghc version.  I assume the test failures I get are caused by this. Any idea how to work around this problem?

**Comment by mgttlinger** [comment]
I will open an issue for nix compatability

**Comment by mgttlinger** [comment]
Ok, I'm at the point where I got everything to detect if we are using a nix shell and then propagate this downwards to the launched stack instance. And the tests now work but I get the following warning:
```
[importify:WARNING] Next errors occured during caching of package: importify-1.0:library
    - Location:
          /workspace/importify/src/Importify/Resolution/Qualified.hs: -1: -1
      Reason:
          /workspace/importify/src/Importify/Resolution/Qualified.hs: hGetContents: invalid
          (invalid byte sequence)
    - Location:
          /workspace/importify/src/Importify/Stack.hs: -1: -1
      Reason:
          /workspace/importify/src/Importify/Stack.hs: hGetContents: invalid argument (invalid
          sequence)
    - Location:
          /workspace/importify/src/Importify/Tree.hs: -1: -1
      Reason:
          /workspace/importify/src/Importify/Tree.hs: hGetContents: invalid argument (invalid
          sequence)
    - Location:
          /workspace/importify/src/Importify/Syntax/Import.hs: -1: -1
      Reason:
          /workspace/importify/src/Importify/Syntax/Import.hs: hGetContents: invalid argument
          byte sequence)
    - Location:
          /workspace/importify/src/Importify/Resolution/Explicit.hs: -1: -1
      Reason:
          /workspace/importify/src/Importify/Resolution/Explicit.hs: hGetContents: invalid
          (invalid byte sequence)
```
and 
```
  subfolder: test/test-data/haskell-names@both/
    01-ImportBothUsedQualified.hs
     # PENDING: No reason given
```
is the only test which is not green. Is this to be expected or is this still a quirk in my setup which I should take care of?

**Comment by ChShersh** [comment]
@mgttlinger Those errors regarding cache of `importify-1.0:library` are very strange. Looks more like errors with encoding...

Regarding PENDING test: this is expected and completely ok.
