### ISSUE TITLE
Feature request: upport adding imports on the fly.

### ISSUE THREAD

**Issue by Wizek** [serokell/importify#63]
https://www.reddit.com/r/haskell/comments/7777df/hack_importify_by_serokell_during_hacktoberfest/dojxjx1/?context=10000

**Comment by ChShersh** [comment]
Thanks for creating issue! But first we need to simply support adding imports...

There's such tool [`halberd`](https://github.com/haskell-suite/halberd/) which can add missing imports. But it's not maintained. And its interface is not very convenient...

**Comment by Wizek** [comment]
Whoops, sorry about the inadvertent duplicate submission on my part. https://github.com/serokell/importify/issues/64 is the better submission indeed.
