### ISSUE TITLE
Make test output more concise

### ISSUE THREAD

**Issue by ChShersh** [serokell/importify#73]
After some recent changes testsuite output contains big absolute paths instead of short one. This should be fixed because test output contains a lot of redundant information.

![screenshot from 2017-10-24 21-01-40](https://user-images.githubusercontent.com/4276606/31959918-c51bde40-b8fe-11e7-88e7-338bd78c874d.png)

**Comment by astynax** [comment]
I can work on this. Full path seems redundant because of test group description (it already contains a subfolder name). Will it be Ok, if paths to test files will contain only a filename?
```
file:unused
  subfolder: test/test-data/base@basic/
    01-Dummy.hs
    02-BoolBool.hs
    ...
```

**Comment by ChShersh** [comment]
@astynax Yes, you're right! Even more: `test/test-data/base@basic/` is too big. It's enough to show only `base@basic`. Thanks for your interest in this issue :)
