### ISSUE TITLE
The function wordWrap drops words when wrapping

### ISSUE THREAD

**Issue by PoJieNie** [serokell/importify#90]
The problem: The function wordWrap in src/Extended/Data/Str.hs will drop words when a wrapping happens.
Description: I copied the function to my Main.hs and randomly copied a line in contributing guide as an example, here is my code:

    module Main where
    import Universum
    import Prelude ()

    import qualified Data.Text as T

    -- this function is directly copied from src/Extended/Data/Str.hs in importify package
    wordWrap :: Int -> String -> Text
    wordWrap n = unlines . map unwords . go 0 [] . words . toText
      where
        go :: Int -> [Text] -> [Text] -> [[Text]]
        go _   row    []  = [row]
        go acc row (w:ws) = let newAcc = acc + T.length w
                            in if newAcc > n
                               then row : go 0 [] ws
                               else go newAcc (row ++ [w]) ws

    main :: IO ()
    main = do
        let str = "We love pull requests from everyone. But, please, don't create PR without corresponding issue. It's always better to discuss your future work first."
        putStrLn $ wordWrap 80 str

The output is:

    We love pull requests from everyone. But, please, don't create PR without corresponding
    It's always better to discuss your future work first.

The expected output is:

    We love pull requests from everyone. But, please, don't create PR without corresponding
    issue. It's always better to discuss your future work first.

and as you can see, the word "issue." disappeared.

**Comment by ChShersh** [comment]
@PoJieNie Thanks for bug report! I will fix implementation of `wordWrap` function.
