### ISSUE TITLE
Ambiguous infix expression

### ISSUE THREAD

**Issue by kfigiela** [serokell/importify#94]
Importify is unable to process some modules when running `importify cache` due to ambiguous infix operators. This results in too many imports being removed from sources. 

According to https://github.com/haskell-suite/haskell-src-exts/issues/72 we can provide fixities to `haskell-src-exts`. I believe operator fixities are not important in terms of importify. I have hardcoded `fixities = Just []` and this helped to remove those warnings (see PR).

**Comment by ChShersh** [comment]
@kfigiela I agree. Problems with fixities really decreased usefulness of `importify`... I'm glad it can be solved in a such simple way!
